version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make run
    env_file:
      - .env
    ports:
      - "${ADMIN_PORT}:${ADMIN_PORT}"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
